Publish: Password requires username
You can't use a password without a username in `uv publish`, which we can catch in clap directly.

New error when using only a password:
```
$ uv publish --password dummy
error: the following required arguments were not provided:
  --username <USERNAME>

Usage: uv.exe publish --username <USERNAME> --password <PASSWORD> [FILES]...

For more information, try '--help'.
```